### ISSUE TITLE
Performance benchmarks

### ISSUE THREAD

**Issue by JustinDrake** [paulmillr/noble-bls12-381#1]
How fast do the various operations run? For example, how many pairings per second?

**Comment by paulmillr** [comment]
The initial goal of this lib was to provide *any* bls12 infrastructure for JS; it must've been totally readable and auditable. A big problem in node community right now is the fact that every dependency has 10 sub-dependencies, all of which may be backdoored.

Right now it's pretty slow. We'd love to increase performance over the time. But it's good enough, if somebody wants to make a wallet.

Added to README:

```
Pairing#test x 1.05 ops/sec ±1.43% (7 runs sampled)
getPublicKey#test x 1,080 ops/sec ±0.88% (85 runs sampled)
sign#test x 16.32 ops/sec ±1.08% (75 runs sampled)
verify#test x 0.48 ops/sec ±0.74% (7 runs sampled)
aggregateSignatures#test x 161 ops/sec ±0.92% (79 runs sampled)
```

**Comment by paulmillr** [comment]
@JustinDrake the recent release is now faster than eth's py_ecc.

Still need to use frobenius endomorphism and vectorial addition chain to make it much faster. Work in progress.

**Comment by paulmillr** [comment]
@JustinDrake 50 pairings per second now.
