### ISSUE TITLE
Signing similar message results in indentical signature?

### ISSUE THREAD

**Issue by KeeJef** [paulmillr/noble-bls12-381#18]
Came across an issue where if i make two messages similar enough i can produce the same signature for two different messages, not sure if i should be hashing messages before passing them to bls.sign()? Documentation seems to suggest bls.sign hashes before signing

`message: Uint8Array | string - message which would be hashed & signed`

```
var bls = require('noble-bls12-381');

testfunction()

async function testfunction() {

  privKey = "970a3e0249bc5e464291d5eee88ae364d8b794f648950055a382a28ed73d655472f218dae342d3ee4566443ff23a78d85580eb4b11954f6286c6cfc67ad1c082"
  message1 = "test"
  message2 = "tes3"

  let signature1 = await bls.sign(message1, privKey)
  let signature2 = await bls.sign(message2, privKey)

  console.log(signature1 +"     "+ signature2)
};
```

Result of this is 

Sig1

```
175,108,55,86,26,251,15,127,253,213,104,43,200,96,1,209,89,116,108,207,203,153,209,235,196,140,78,183,134,165,209,6,236,115,195,3,34,60,8,206,114,48,62,206,39,129,17,62,0,138,178,86,37,175,157,169,168,138,78,130,147,204,36,130,255,89,38,124,134,252,16,192,209,18,225,6,107,203,116,129,81,194,75,230,226,178,210,79,239,165,8,110,90,253,199,246  
```
Sig2

```
175,108,55,86,26,251,15,127,253,213,104,43,200,96,1,209,89,116,108,207,203,153,209,235,196,140,78,183,134,165,209,6,236,115,195,3,34,60,8,206,114,48,62,206,39,129,17,62,0,138,178,86,37,175,157,169,168,138,78,130,147,204,36,130,255,89,38,124,134,252,16,192,209,18,225,6,107,203,116,129,81,194,75,230,226,178,210,79,239,165,8,110,90,253,199,246
```

Which are identical, despite signing two different messages "test" and "tes3"

**Comment by paulmillr** [comment]
message must actually be `hex`. In cryptography, you don't sign usually sign "message", instead, you sign its hash. 

so, do sha256("test") and use the result as a message. i'll mention this in readme.

**Comment by paulmillr** [comment]
if you don't want to hash msg, you can convert it to byte array instead: `new TextEncoder().encode('test')`

**Comment by KeeJef** [comment]
Yeah sweet, ill just hash before signing, just wasnt 100% clear from the docs

**Comment by paulmillr** [comment]
@KeeJef i've made the checks strict, so "test3" would throw now.

**Comment by paulmillr** [comment]
Also, for BLS in particular, there is no need to "hash" messages — because we are using `hash-to-curve` standard which can handle arbitrary strings — and it hashes by itself. So, feel free to do `new TextEncoder().encode('test')`.
