### ISSUE TITLE
Sync API

### ISSUE THREAD

**Issue by dapplion** [paulmillr/noble-bls12-381#19]
I was attempting to do some benchmark between the existing BLS implementations however this library has an async API which breaks with what https://github.com/ChainSafe/bls currently has. I see that the reason of the async API is the hash function. Could a sync version of `sha256` be used so the API stays sync?

**Comment by paulmillr** [comment]
That will increase the size of the bundle. Why?

Chainsafe/bls is also async. It requires wasm import, which is async operation. Noble's import is sync.

My benchmark software (micro-bmark package) can measure async actions.
