### ISSUE TITLE
Support constructing G1 and G2 points from their uncompressed forms

### ISSUE THREAD

**Issue by RomarQ** [paulmillr/noble-bls12-381#21]
Hi @paulmillr,

Thanks for the great work.

Are you planning to add support for constructing points G1 and G2 from their uncompressed forms?
https://docs.rs/bls12_381/0.4.0/bls12_381/struct.G1Affine.html#method.from_uncompressed
https://docs.rs/bls12_381/0.4.0/bls12_381/struct.G2Affine.html#method.from_uncompressed

In PR #22:
- https://docs.rs/bls12_381/0.4.0/bls12_381/struct.G1Affine.html#method.to_uncompressed
- https://docs.rs/bls12_381/0.4.0/bls12_381/struct.G2Affine.html#method.to_uncompressed

**Comment by paulmillr** [comment]
Sure, why not. Any pull request would be appreciated.

**Comment by RomarQ** [comment]
I could give it a try this week once I find some time to do it.

**Comment by RomarQ** [comment]
Is the naming toCompressed`Hex` intended? It returns an array of bytes.

The PR above keeps the naming.

**Comment by RomarQ** [comment]
Hi @paulmillr,

I was implementing the `from_uncompressed` part and I think I've it ready (just need to add some more tests)

Since the version is not `1.0.0` yet, is it fine to replace `fromSignature` completely with `fromHex` and `fromRawBytes`? Or, should it be deprecated?

**Comment by paulmillr** [comment]
`fromHex` is able to take both `bytes` and `hex string`, so no need for two methods.

As for `fromSignature`, we should not replace it, because it is possible to have signatures over G1 (not supported yet). Signatures have different logic.

**Comment by paulmillr** [comment]
feel free to add from_uncompressed

**Comment by paulmillr** [comment]
Thank you for the good work.
