### ISSUE TITLE
Compatibility with Filecoin

### ISSUE THREAD

**Issue by dholms** [paulmillr/noble-bls12-381#24]
Hey there :slightly_smiling_face: 

I'm trying to use this library for signing Filecoin messages. Specifically the signature/pubkey aggregation tools which aren't available in the [Filecoin WASM lib](https://github.com/Zondax/filecoin-signing-tools)

However, I've noticed that the public keys don't match up: 

```
private key: 4eeb8f66c557115a7ec37e7debc2b0b9130f0d4a2b74cd64ec478a88e2ac052c
public key (from zondax lib):  84b1498c9332a1639f67c8e2fc49a9bae0ecfb68cb6182f12ad8c30cc62e8c37029aeaeaa5e1685fb2656792b926bc8d
public key (from noble-bls12-381): ac2d1dc191f5f8766ac7cef6877c10ff928b7a8217e1f64ca069499242f91e5f50064c8ee2b337e0b6a68b6808bc11f0
```

Do you have any quick thoughts on the matter. I'm relatively new to BLS, but from what I can tell, these should all be on the same pair of 2 curves, and I've verified that both this lib & filecoin use G1 for public keys and G2 for signatures.

I've also verified that the zondax lib calculates the same public key as the lotus node does (Go implementation of Filecoin).

Is there something else that I'm not thinking of?

**Comment by paulmillr** [comment]
Could you show the code which is used to create public keys a) with noble-bls b) with filecoin/bls-sigs?

**Comment by paulmillr** [comment]
I'm thinking you're using `KeyGen` function (https://tools.ietf.org/html/draft-irtf-cfrg-bls-signature-02#section-2.3) instead of `SkToPk`. If you need `KeyGen`, use https://github.com/paulmillr/bls12-381-keygen

noble-BLS works properly, you can verify it by checking bls12-381-keygen's readme example - it generates proper eth keys.

**Comment by dholms** [comment]
Sure thing.

Here is the simplest example:
```js
const zondax = require('@zondax/filecoin-signing-tools')
const noble = require('noble-bls12-381')

const privateKeyHex = '4eeb8f66c557115a7ec37e7debc2b0b9130f0d4a2b74cd64ec478a88e2ac052c'
const privateKeyBuf = Buffer.from(privateKeyHex, 'hex')

const publicKeyHexNoble = noble.getPublicKey(privateKeyHex)
const publicKeyHexZondax = zondax.keyRecoverBLS(privateKeyBuf, true).public_hexstring

console.log('privateKeyHex:', privateKeyHex)
console.log('publicKeyHexNoble:', publicKeyHexNoble)
console.log('publicKeyHexZondax:', publicKeyHexZondax)
```
Output:
```
privateKeyHex: 4eeb8f66c557115a7ec37e7debc2b0b9130f0d4a2b74cd64ec478a88e2ac052c
publicKeyHexNoble: ac2d1dc191f5f8766ac7cef6877c10ff928b7a8217e1f64ca069499242f91e5f50064c8ee2b337e0b6a68b6808bc11f0
publicKeyHexZondax: 84b1498c9332a1639f67c8e2fc49a9bae0ecfb68cb6182f12ad8c30cc62e8c37029aeaeaa5e1685fb2656792b926bc8d
```

**Comment by dholms** [comment]
I've verified that the address derived from `publicKeyHexZondax` matches the address for the same private key stored in a lotus node. But it's totally possible that this is an error on my end with the use of this library.

I'll take a look at the links you included.

Thanks for the quick response :slightly_smiling_face:

**Comment by paulmillr** [comment]
yeah -- i'm not sure what happens with the `keyRecoverBLS`, but if bls12-381-keygen works properly with ETH2, then noble is correct.

**Comment by dholms** [comment]
Okay I've confirmed that the public keys from this library do match the public keys from other ETH2 libraries. But those are different from the public keys derived for Filecoin. The _does_ derive a matching public key to Lotus (the reference implementation of Filecoin).

Feel free to close the issue as I know this library is targeted at ETH2. 

One more quick question if you don't mind: am I correct in my understanding that BLS12-381 refers to a specific pair of curves? I know that in some implementations, public keys can be on G1 & signatures on G2 or vice versa. Are you aware of any other params that change that could be causing this discrepancy?

Thanks!

**Comment by dholms** [comment]
Good news! We've figured out the issue here: ETH2 uses big endian for private keys and Filecoin uses little endian. I'd thought to check the endianess of the public keys but had neglected to check it for private keys

**Comment by paulmillr** [comment]
Ah, the old endianness problem. That makes sense.

**Comment by paulmillr** [comment]
I have added a readme clarification
