### ISSUE TITLE
Multiply G1, G2 by Fr

### ISSUE THREAD

**Issue by RomarQ** [paulmillr/noble-bls12-381#25]
Does the lib support multiplication of `G1`, `G2` by `Fr`? 

I don't see it in the code, but I could be wrong.

**Comment by paulmillr** [comment]
What is your use case?

**Comment by paulmillr** [comment]
I mean, `Fr` is simply a BigInt underneath.

**Comment by RomarQ** [comment]
I was missing `little endian` to `big endian` conversion.

Closing the issue.
