### ISSUE TITLE
Regarding the support for the Bls12381G2KeyPair.ts in bls12381-key-pair 

### ISSUE THREAD

**Issue by forsalim12** [paulmillr/noble-bls12-381#27]
Hi, 
We are using noble-bls12-381 library in our project. And we also have to use the Bls12381G2KeyPair.ts > bls12381-key-pair library in our project. 
Now I would like to know whether the noble-bls12-381 could support the Bls12381G2KeyPair.ts  library. 
Please let me know. 
As explained above we will have to use the Bls12381G2KeyPair.ts  library from noble-bls12-381.

My email id : smkhan925@gmail.com

**Comment by paulmillr** [comment]
It's them who should support noble - not us supporting them.
