### ISSUE TITLE
Compatibility with Chia

### ISSUE THREAD

**Issue by vae520283995** [paulmillr/noble-bls12-381#28]
@paulmillr Hi paulmillr,
Is noble-bls12-381 compatible with https://github.com/Chia-Network/bls-signatures?

**Comment by paulmillr** [comment]
Yes. 

Bls library compatibility consists of three main things:

1. Specification version -- both libs are using ietf spec
2. G1 pubkeys, G2 signatures VERSUS G1 sigs, G2 pubkeys. both are using G1 pubkeys. 
3. DST vector aka salt/pepper. Which can be changed with bls.DST (see readme). I don't know which dst they're using, but it may be the same. If it's not, you can change it.

**Comment by vae520283995** [comment]
> Yes.
> 
> Bls library compatibility consists of three main things:
> 
> 1. Specification version -- both libs are using ietf spec
> 2. G1 pubkeys, G2 signatures VERSUS G1 sigs, G2 pubkeys. both are using G1 pubkeys.
> 3. DST vector aka salt/pepper. Which can be changed with bls.DST (see readme). I don't know which dst they're using, but it may be the same. If it's not, you can change it.

As you said, only need to modify DST to be compatible, thank you
