### ISSUE TITLE
Expose non-signature API

### ISSUE THREAD

**Issue by JustinDrake** [paulmillr/noble-bls12-381#3]
As specified in the introduction, BLS12-381 is used for non-signature applications such as SNARKs. It may make sense to expose a non-signature API (e.g. directly expose the pairing function).

**Comment by paulmillr** [comment]
Done! The commit is 7e11c0e4be4100ffeb24c2cf6e8ef55f9fba29ff

Do you think the naming makes sense? We expose `bls.pairing(4dPoint, 2dPoint)` method right now.
