### ISSUE TITLE
Are there any plans to write a blog about bls12-381

### ISSUE THREAD

**Issue by vae520283995** [paulmillr/noble-bls12-381#31]
@paulmillr Hi,
[Learning fast elliptic-curve cryptography in JS](https://paulmillr.com/posts/noble-secp256k1-fast-ecc/) This blog helped me a lot and gave me an in-depth understanding of secp256k1, but bls12-381 is very different from secp256k1 and ed25519, which makes me very distressed. Do you have any plans to write an blog about bls12-381?

**Comment by paulmillr** [comment]
no immediate plans, maybe some day in the future

**Comment by paulmillr** [comment]
the repo got merged into [paulmillr/noble-curves](https://github.com/paulmillr/noble-curves) and is now deprecated.
