### ISSUE TITLE
Support for Deno runtime

### ISSUE THREAD

**Issue by saad3645** [paulmillr/noble-bls12-381#36]
Currently, this module does not completely support the deno runtime environment.
When trying to use this with deno, the following error occurs:

```
error: Import 'https://deno.land/x/bls12_381@0.14.1/math' failed: 404 Not Found
    at https://deno.land/x/bls12_381@0.14.1/index.ts:14:0
```

This is happening because deno requires an explicit extension for import statements. For example, `'./math.ts'` instead of `'./math'`.

**Comment by paulmillr** [comment]
so how do we keep *one* import for both node and deno?

**Comment by paulmillr** [comment]
Done! Use 1.1.0

**Comment by CluEleSsUK** [comment]
I'm currently seeing the following when trying to use this on deno:
```
error: Module not found "https://deno.land/x/bls12_381@1.3.0/math.js".
    at https://deno.land/x/bls12_381@1.3.0/index.ts:20:8
```
I dunno if this is a regression or I'm doing something stupid but it seems similar to above
