### ISSUE TITLE
Option to choose curve for hash_to_field

### ISSUE THREAD

**Issue by iancoleman** [paulmillr/noble-bls12-381#37]
Just a quick question regarding hash_to_field as a way to convert arbitrary bytes to Fr

In the ietf draft it says
https://www.ietf.org/archive/id/draft-irtf-cfrg-hash-to-curve-10.html#section-5-4
"The hash_to_field function is also suitable for securely hashing to scalars. For example, when hashing to scalars for an elliptic curve (sub)group with prime order r, it suffices to instantiate hash_to_curve with target field GF(r)."

I've modified noble-bls12-381 locally allowing hash_to_field to take a 4th parameter, `field = math_1.CURVE.P` and then passing in `math_1.CURVE.r` to generate bytes for Fr using hash_to_field (also exported hash_to_field function in utils).

From what I can see this is legitimate use of hash_to_field. Is there anything you're aware of that would make this a bad idea?

The idea doesn't seem widely used (unlike hash_g2) but it seems like it should be a robust and standardized kdf from arbitrary bytes to key without rejection sampling. Am I understanding it correctly?

**Comment by paulmillr** [comment]
I think you're correct. Care to submit a PR which will replace rejection sampling with this? (also, i'm curious about its performance)

**Comment by paulmillr** [comment]
Actually `randomPrivateKey` is synchronous, while the hash_to_field is not, so not sure about the PR.

**Comment by iancoleman** [comment]
They're different things though.

`randomPrivateKey` generates a random key from no input.

`hash_to_field` turns some input into some deterministic output.

`randomPrivateKey` could be done without rejection sampling though:
`randomBytes = getRandomValues(my32bytes); hash_to_field(randomBytes)`

Previously I've been hashing the input, rejecting it if `hash > CURVE.r` then hashing repeatedly until `output < CURVE.r`. This is not following any standard process so I'd like to replace it with `hash_to_field` if it makes sense to do so.

> Care to submit a PR

Yeah can do if the above points make sense.

**Comment by paulmillr** [comment]
I understand — they are different and this:

>randomPrivateKey could be done without rejection sampling though: randomBytes = getRandomValues(my32bytes); hash_to_field(randomBytes)

is exactly what i've meant. But hash_to_field is async. which means we'll break the api. not sure if it's worth it.

**Comment by iancoleman** [comment]
Ah yeah ok I understand now.

The functionality is still useful to me (not for randomPrivateKey, for other reasons), so I'll submit a PR and we can look at it and discuss further from there.
