### ISSUE TITLE
Add support for G2 public keys with G1 signatures

### ISSUE THREAD

**Issue by 0xAaCE** [paulmillr/noble-bls12-381#43]
# Not working with DFinity bls

## Description

When I tried to use this library instead of BLS_verify implementation into agent-js library I cannot make it work. I only obtained `Error: Invalid G1 point: not on curve Fp`. Going into agent-rs library to watch what the original implementation does, I realize that in DFinity libraries PublicKey is G2 point and signature is a G1 point. So, there is anyway to fix this problem?

agent-rs library where implement bls verify https://github.com/dfinity/agent-rs/blob/88606ecc8288592a7bcc1c8d23e877914b3b31da/ic-agent/src/bls/bls12381/bls.rs#L137-L171

**Comment by paulmillr** [comment]
> DFinity libraries PublicKey is G2 point and signature is a G1 point

The point is described in our README. We only support G1 pubkeys. So, that's it. Contributions are welcome.

**Comment by christianpaquin** [comment]
> The point is described in our README. We only support G1 pubkeys. So, that's it. Contributions are welcome.

I'd like to check if there are updates on this. I'm writing a TypeScript [BBS signatures](https://github.com/decentralized-identity/bbs-signature) implementation, and using your (great!) library for the BLS support, but BBS fixes sig in G1 and keys in G2. I'm hoping to contribute that underlying code here; unless work in already underway... (?)

**Comment by paulmillr** [comment]
No work has been done on this

**Comment by paulmillr** [comment]
the repo got merged into [paulmillr/noble-curves](https://github.com/paulmillr/noble-curves) and is now deprecated.
