### ISSUE TITLE
Possible missing edge case in `modexp` function

### ISSUE THREAD

**Issue by acolytec3** [paulmillr/noble-bls12-381#49]
Following your suggestion [here](https://github.com/ethereumjs/ethereumjs-monorepo/pull/1652#issuecomment-1020341342), I implemented your `modexp` function in our bigint conversion PR.  I may have uncovered an edge case not addressed in your method and wanted to get your input.  In the [`modexptests`](https://github.com/ethereum/tests/blob/develop/GeneralStateTests/stPreCompiledContracts/modexpTests.json) in the `Ethereum/Tests` repo, there are a couple of tests that generate a call to the `modexp` method with a 0 for the exponent and some other value for the modulo and one case in particular passes in a = 0, power = 0, and modulo 1.  In your method as currently coded, this would result in a 1 being returned though the expected result in the ethereum test is 0 (I believe based on the understanding that any base ^ 0 = 1 and then 1 % 1 = 0.  Does this look like a possible edge case that your code doesn't account for?  I've added in a check where the exponent = 0 and then returned 1 % modulo in our code and this satisfies the test case and I believe is a correct result, at least on some definitions of exponentiation (though I'm far from an expert in this area) so I wanted to raise it and get your input.

**Comment by paulmillr** [comment]
Hi @acolytec3

I'm curious why pow(0, 0, exp=1) would return 1. mod() cannot return number == modulo.

Seems like eth test is wrong. I think we should follow Python built-in:

pow(0, 0, 1) outputs 0 in python.

**Comment by paulmillr** [comment]
Fixed now
