### ISSUE TITLE
HashToCurve on G1 points

### ISSUE THREAD

**Issue by AnomalRoil** [paulmillr/noble-bls12-381#55]
I need to perform hash to curve on G1, like this:
https://github.com/kilic/bls12-381/blob/6045b0235e36793a56ad254cc6d2af650c3a584f/g1.go#L827-L846

Is that currently possible with Noble? I wasn't able to find the required function.

If not, would you consider implementing it?   
(We'd be happy to sponsor its implementation, since it's necessary to implement a JS lib compatible with our identity-based encryption scheme: https://github.com/drand/kyber/blob/master/encrypt/ibe/ibe.go#L47.)

**Comment by paulmillr** [comment]
Yeah, sure, why not. Would you be able to sponsor via GitHub sponsors? I will set it up in a bit.

**Comment by AnomalRoil** [comment]
We're still figuring this out on our side, sorry for the delay here! But Gitcoin seems like a probably good way of doing that to us. WDYT?

**Comment by christianpaquin** [comment]
This [commit](https://github.com/paulmillr/noble-bls12-381/commit/d53cef0f002be121ead5789e0849ea5bf74962e8) implements the requested feature (part of v1.4.0); this can probably closed.

**Comment by paulmillr** [comment]
Exactly - kudos to Protocol Labs for sponsoring this!
