### ISSUE TITLE
The default implementation is incompatible with Ethereum specification

### ISSUE THREAD

**Issue by shresthagrawal** [paulmillr/noble-bls12-381#59]
This implementation uses `BLS_SIG_BLS12381G2_XMD:SHA-256_SSWU_RO_NUL_` while Ethereum uses `BLS_SIG_BLS12381G2_XMD:SHA-256_SSWU_RO_POP_`.  To verify Ethereum signatures one has to set the DST label (`bls.utils.setDSTLabel('BLS_SIG_BLS12381G2_XMD:SHA-256_SSWU_RO_POP_')`). Perhaps worth mentioning this in the README.

**Comment by paulmillr** [comment]
the repo got merged into [paulmillr/noble-curves](https://github.com/paulmillr/noble-curves) and is now deprecated.
