### ISSUE TITLE
Wrong serialisation of point at infinity?

### ISSUE THREAD

**Issue by mrhornsby** [paulmillr/noble-bls12-381#6]
Hi,

I may be wrong but I think the serialisation of the point at infinity is wrong. I would expect the two high order bits to be set (compressed = true, infinity = true), but converting `Z1` to a private key has only the compressed bit set:

`800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000`

As opposed to:

`C00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000`

I thought I'd double check by deserialising again and comparing the points:

```
console.log(Z1);
console.log(publicKeyToG1(publicKeyFromG1(Z1)));
```

This produces the following:

```
Point {
  x: Fp { _value: 1n },
  y: Fp { _value: 1n },
  z: Fp { _value: 0n },
  C: [Function: Fp] {
    ORDER: 4002409555221667393417789825735904156556882819939007885332058136124031650490837864442687629129015664037894272559787n
  }
}
Point {
  x: Fp { _value: 0n },
  y: Fp { _value: 2n },
  z: Fp { _value: 1n },
  C: [Function: Fp] {
    ORDER: 4002409555221667393417789825735904156556882819939007885332058136124031650490837864442687629129015664037894272559787n
  }
}
```

Thanks

Mark

**Comment by paulmillr** [comment]
Hi Mark,

This seems to be the case. We need to fix it.

**Comment by mrhornsby** [comment]
👍 

I believe using [projective coordinates the point at infinity is generally represented as (0, 1, 0)](https://crypto.stanford.edu/pbc/notes/elliptic/group.html). I'll try to take a look later today to see if I can provide a PR to fix this.

**Comment by mrhornsby** [comment]
Hi,

Finally got around to working on this [here](https://github.com/mrhornsby/noble-bls12-381). I've fixed G1 serialisation (it wasn't a lot of code in the end!), I just want to review G2 and the de-serialisation routines then I'll send over a PR.

Mark

**Comment by paulmillr** [comment]
Perfect!
