### ISSUE TITLE
how to understand the precomputes of Miller Loop in noble-bls12-381?

### ISSUE THREAD

**Issue by xichan-ms** [paulmillr/noble-bls12-381#61]
Miller Loop is a basic but important algorithm to calculate pairing.

noble-bls12-381 is a clean and independent implementation of bls12-381 pairing without library dependency.

I know the original Miller Loop algorithm, but in above implementation, there exist a tricky pairingPrecomputes, is there any material or description about this pre-computing? thanks a lot

https://github.com/paulmillr/noble-bls12-381/blob/main/index.ts#L395

**Comment by paulmillr** [comment]
Not really, just this function. You can think of it as elliptic curve scalar multiplication precomputes (walk bit-by-bit on a scalar/number).

https://github.com/paulmillr/noble-bls12-381/blob/b06f567511c06e016032d8c8548c4759a63fb1d8/math.ts#L1331

**Comment by xichan-ms** [comment]
could you give us more detailed info about the calcPairingPrecomputes? such as: paper or blog

there seems some computing optimization, which is kind of tricky. thanks a lot.

**Comment by paulmillr** [comment]
No paper. No blog. Just this code. You will need to investigate it by yourself.

**Comment by xichan-ms** [comment]
ok, thanks
