### ISSUE TITLE
hashToCurve defaults to the G2 DST even on G1

### ISSUE THREAD

**Issue by AnomalRoil** [paulmillr/noble-bls12-381#63]
As you can see here:
https://github.com/paulmillr/noble-bls12-381/blob/b06f567511c06e016032d8c8548c4759a63fb1d8/index.ts#L331-L346
the code will default to the [htfDefaults](https://github.com/paulmillr/noble-bls12-381/blob/b06f567511c06e016032d8c8548c4759a63fb1d8/index.ts#L60-L64) which are meant for G2 when none are passed:
```
const htfDefaults = {
    DST: 'BLS_SIG_BLS12381G2_XMD:SHA-256_SSWU_RO_NUL_',
    p: math_js_1.CURVE.P,
    m: 2,
    k: 128,
    expand: true,
    hash: sha256,
};
```

This could be an issue for people meaning to use the library to do things on G1 and not providing their own DST or their own test vectors and thus not detecting the issue. Overall it doesn't look like a big security problem, but it does cause interoperability issues.

**Comment by AnomalRoil** [comment]
(it does says so in the [comment](https://github.com/paulmillr/noble-bls12-381/blob/b06f567511c06e016032d8c8548c4759a63fb1d8/index.ts#L50) of the htfDefaults, but it's not obvious and somewhat underdocumented in the actual HashToCurve code)

**Comment by paulmillr** [comment]
Yeah, this is not great, but I would still argue for explicitly specifying DST every time. 

I don't think there's such thing as a "standard" dst, is there? NUL, POP, all different ones can be made standard

**Comment by paulmillr** [comment]
Actually, this repository is deprecated and should not be used. 

I've thought we're discussing the issue in https://github.com/paulmillr/noble-curves repo
